apiVersion: apps/v1
kind: Deployment
metadata:
  name: magalu-app
  namespace: magalu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magalu-app
  template:
    metadata:
      labels:
        app: magalu-app
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

            - name: cache
              mountPath: /var/cache/nginx

          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: magalu-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: magalu-secret
                  key: password

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

      volumes:
        - name: html
          configMap:
            name: magalu-html

        - name: cache
          emptyDir: {}