apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: magalu-secret
  namespace: magalu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: magalu-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: secret/magalu
        property: username

    - secretKey: password
      remoteRef:
        key: secret/magalu
        property: password